### ISSUE TITLE
UUPDownload fails for Lenovo/YogaC630

### ISSUE THREAD

**Issue by lumag** [WOA-Project/Qualcomm-Reference-Drivers#7]
I attempted to download the Lenovo/YogaC630 drivers using the `refresh.sh` / `UUPDownload.AMD64` tool, but got the following crash:

```
[02:48:11][Information] UnifiedUpdatePlatform.Media.Download 3.1.9.2 - Download from the Microsoft Unified Update Platform
[02:48:11][Information] Copyright (c) Gustave Monce and Contributors
[02:48:11][Information] https://github.com/gus33000/UUPMediaCreator

[02:48:11][Information] This program comes with ABSOLUTELY NO WARRANTY.
[02:48:11][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[02:48:11][Information] This software contains work derived from libmspack licensed under the LGPL-2.1 license.
[02:48:11][Information] (C) 2003-2004 Stuart Caie.
[02:48:11][Information] (C) 2011 Ali Scissons.

[02:48:12][Information] \LENOVO\YogaC630
[02:48:12][Information] Checking for updates...
[02:48:13][Information] 0: Title: LENOVO - System Hardware Update - 9/6/2019
[02:48:13][Information] 0: Description: System Manifest
[02:48:13][Information] Gathering update metadata...
[02:48:13][Information] Checking for updates... 200.0.0.0 / 200.0.19.0
[02:48:14][   Error   ] No updates found that matched the specified criteria.
[02:48:14][Information] Checking for updates... 200.0.1.0 / 200.0.19.0
[02:48:14][Information] Title: LENOVO - System Hardware Update - 9/12/2018
[02:48:14][Information] Description: System Manifest
[02:48:15][   Error   ] Something happened.
[02:48:15][   Error   ] One or more errors occurred. (Index was outside the bounds of the array.)
[02:48:15][   Error   ]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at UUPDownload.DownloadRequest.ProcessDrivers.ParseDownloadOptions(DownloadRequestOptions opts)
   at UUPDownload.Program.<>c__DisplayClass2_0.<Main>b__4()
   at UUPDownload.Program.WrapAction(Action a)
[02:48:15][   Error   ] Index was outside the bounds of the array.
[02:48:15][   Error   ]    at UnifiedUpdatePlatform.Services.WindowsUpdate.Downloads.UpdateUtils.ProcessUpdateAsync(UpdateData update, String pOutputFolder, MachineType MachineType, IProgress`1 generalDownloadProgress, String Language, String Edition, Boolean WriteMetadata, Boolean UseAutomaticDownloadFolder, Int32 downloadThreads)
   at UUPDownload.DownloadRequest.ProcessDrivers.ProcessDriverPlan(DriverPlan DriverPlan, OSSkuId ReportingSku, String ReportingVersion, MachineType MachineType, String FlightRing, String FlightingBranchName, String BranchReadinessLevel, String CurrentBranch, String ReleaseType, Boolean SyncCurrentVersionOnly, String ContentType, String Mail, String Password, String Language, String Edition, String RepoLocation)
   at UUPDownload.DownloadRequest.ProcessDrivers.CheckAndDownloadUpdates(OSSkuId ReportingSku, String ReportingVersion, MachineType MachineType, String FlightRing, String FlightingBranchName, String BranchReadinessLevel, String CurrentBranch, String ReleaseType, Boolean SyncCurrentVersionOnly, String ContentType, String Mail, String Password, String Language, String Edition, String OutputFolder)
```

For the reference, the DriversConfig is the following:

```
[
  {
    "outputFolder": "\\LENOVO\\YogaC630",
    "guid": "{43b71948-9c47-5372-a5cb-18db47bb873f}",
    "filteredIds": [],
    "excludedIds": []
  }
]
```

**Comment by lumag** [comment]
Found the issue, should be fixed with https://github.com/gus33000/UUPMediaCreator/pull/226
